---
title: "Untitled"
format: html
---

# Clean and wrangle data

## Set up

```{r}
#| label: library
library(dplyr)
library(tidyr)
library(readr)
```


## Load data
```{r}
#| label: load
catch_orig <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

## Clean and reshape data

```{r}
colnames(catch_orig)
head(catch_orig)
summary(catch_orig)
glimpse(catch_orig)
```

```{r}
catch_data <- catch_orig %>% 
    select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
#check it
head(catch_data)

catch_data2 <- catch_orig %>% 
    select(Region,
    Year,
    Chinook,
    Sockeye,
    Coho,
    Pink,
    Chum,
    total= All,
    notes= notesRegCode)

# Make the chinook col numeric
catch_clean <- catch_data %>% 
    mutate(Chinook = as.numeric(Chinook))

# NAs introduced
is.na(catch_clean$Chinook)
i <- which(is.na(catch_clean$Chinook))

catch_data[i,] # was an I not a 1

catch_clean <- catch_data %>% 
    mutate(Chinook = if_else(
        Chinook == "I",
        true = "1", #because this col is character, need to put quotes
        false =Chinook),
        Chinook = as.numeric(Chinook)
    )
```

### Go from wider to longer

```{r}
catch_long <- catch_clean %>% 
    pivot_longer(cols = -c(Region, Year),
    names_to = "species",
    values_to = "catch_thousands")
head(catch_long)
```

### Go from long back to wide data

```{r}
catch_wide <- catch_long %>% 
    pivot_wider(names_from = species,
    values_from = catch_thousands)
head(catch_wide)
```

## Convert to fish numbers

```{r}
catch_long <- catch_long %>% 
    mutate(catch = catch_thousands * 1000) %>% 
    select(-catch_thousands)
head(catch_long)
```

```{r grouping}
mean_region <- catch_long %>% 
    group_by(Region) %>% 
    summarize(mean_catch = mean(catch, na.rm= TRUE), .groups= "drop") %>% 
    arrange(mean_catch) #can also do arrange(desc(mean_catch))

```

```{r}
sse_catch <- catch_long %>% 
    filter(Region == "SSE")

```

## Experiment with unite and separate

```{r}
sites_df <- data.frame(site = c("HAW-101", "HAW-103", "OAH-320", "OAH-219", "MAU-039"))

# Check that out
head(sites_df)

sites_df <- sites_df %>% 
    separate_wider_delim(cols= site,
    delim= "-",
    names = c("island", "site_number"),
    cols_remove = FALSE)
```

```{r}
dates_df <- data.frame(
    year  = rep(x = "1930", times = 3),
    month = rep(x = "12",   times = 3),
    day   = 14:16)

# Check that
dates_df

dates_df %>% 
    unite(col= date,
    year, month, day,
    sep = "-",
    remove= FALSE)
```
