---
title: "Data Visualization"
author: "LMcCormick"
format: html
---

## Set up
```{r}
### Data wrangling
library(readr)
library(here)      ### for robust relative file paths
library(dplyr)
library(tidyr)
library(forcats)   ### tools for working with factors (e.g., reordering)
library(janitor)   ### clean column names

### Visualization
library(ggplot2)

### Interactive output
library(plotly)
library(DT)
library(leaflet)
```

## Load the data
```{r}
# read in data from the data directory after manually downloading data 
delta_visits_raw <- read_csv(here("data/Socioecological_monitoring_data.csv"))
# or delta_visits_raw <- read_csv("https://tinyurl.com/delta-activities")
```

## Explore the data

```{r}
colnames(delta_visits_raw)

glimpse(delta_visits_raw)
```


```{r}
delta_visits <- delta_visits_raw %>%
  janitor::clean_names()

```

```{r}
visits_long <- delta_visits %>%
  tidyr::pivot_longer(
    cols = c(sm_boat, med_boat, lrg_boat, bank_angler, scientist, cars),
    names_to = "visitor_type",
    values_to = "quantity"
  ) %>%
  ### shorten the long name:
  dplyr::rename(restore_loc = eco_restore_approximate_location) %>%
  ### drop the notes column:
  dplyr::select(-notes)

glimpse(visits_long)
```

```{r}
daily_visits_loc <- visits_long %>%
    dplyr::group_by(restore_loc, date, visitor_type) %>% 
    dplyr::summarize(daily_visits = sum(quantity), .groups = 'drop')
    
glimpse(daily_visits_loc)

ggplot(data = daily_visits_loc,
       mapping = aes(x = restore_loc, y = daily_visits)) +
  geom_col() + 
  labs(title = 'Plot title')
```

```{r}
daily_boats_filtered <- daily_visits_loc %>%
    filter(daily_visits < 30,
           visitor_type %in% c("sm_boat", "med_boat", "lrg_boat"))

```

```{r}
daily_visits_totals <- daily_visits_loc %>%
  group_by(restore_loc) %>%
  mutate(total = sum(daily_visits)) %>%
  ungroup() %>%
  mutate(restore_loc = fct_reorder(restore_loc, desc(total)))

```

### Facet wrap plots

```{r}
facet_plot <- ggplot(data = daily_visits_totals,
       aes(x = visitor_type, y = daily_visits,
           fill = visitor_type)) +
    geom_col() +
    facet_wrap(~restore_loc,
               scales = "free_y",
               ncol   = 5,
               nrow   = 2) +
    scale_fill_viridis_d() +
    labs(x        = "Type of visitor",
         y        = "Number of Visits",
         title    = "Total Number of Visits to Delta Restoration Areas",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.x    = element_blank(),
          axis.text.x     = element_blank())

facet_plot
```

### Add plotly

```{r}
ggplotly(facet_plot, tooltip = c('x', 'y'))
```

```{r}
#| echo: false
ggsave(here("figures/visit_restore_site_facet.jpg"), 
       plot = facet_plot, 
       width = 12, height = 8, units = "in")
```

```{r}
datatable(delta_visits)
```

